www/config/routes.rb
DealmylifeCom::Application.routes.draw do
  
  match "auth/:provider/callback" => "authentications#create"
  match "account/login" => "account#login", :as => :login
  match "account/logout" => "account#logout", :as => :logout
  match "account/reset_password" => "account#reset_password", :as => :reset_password
  match "click" => "clicks#new"
  
  resources :authentications
  
    resources :users, :except => [ :show, :new_user ] do
      
      put :enable, :on => :member
      put :disable, :on => :member
      
      match "roles" => "roles#index"
      put "role" => "roles#update"
      delete "role" => "roles#destroy"
      
      match "widgets" => "widgets#list"
      put "widget" => "widgets#assign"
      delete "widget" => "widgets#remove"
      
      match "categories" => "user_categories#index"
      put "category" => "user_categories#update"
      delete "category" => "user_categories#destroy"
      
    end
  
  resources :profiles, :except => [:new, :create] do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  namespace :profile do
    resources :addresses, :controller => "profile_addresses" do
      put :default, :on => :member
    end
  end
  

  resources :partners do
    put :enable, :on => :member
    put :disable, :on => :member
    
    resources :partner_categories, :controller => "partner_categories", :path => :categories, :as => :categories
    
  end

  
=begin
  resources :attribute_groups do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :attributes do
    put :enable, :on => :member
    put :disable, :on => :member
  end
=end
  
  resources :widgets do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :pages do
    put :enable, :on => :member
    put :disable, :on => :member
  end

  resources :categories
  
  match "partners/:id/updatefile" => "partners#updatefile", :as => :updatefile
  
  match "account/edit" => "users#edit", :as => :edit_account
  match "profile/edit" => "profiles#edit", :as => :edit_profile
  match "profile" => "profiles#show", :as => :show_profile
  
  match "page/:permalink" => "pages#show_by_permalink", :as => :permalink
  
  match ":controller(/:action(/:id))"
  

  root :to => "partners#show_all", :as => :index

end

www/app/models/attribute_group.rb
class AttributeGroup < ActiveRecord::Base
	attr_accessible :enabled
	
	validates_presence_of :name
	
	validates_length_of :name, :within => 3..64
	
	has_many :attributes	# This breaks things, but seems like it should be correct
	#has_one :attribute
	
end

www/app/controllers/attribute_groups_controller.rb
class AttributeGroupsController < ApplicationController
	before_filter :check_developer_role
	before_filter :login_required
	
	# GET /attribute_groups
	# GET /attribute_groups.json
	def index
		@attribute_groups = AttributeGroup.all

		respond_to do |format|
			format.html # index.html.erb
			format.json	{ render json: @attribute_groups }
		end
	end

	# GET /attribute_groups/1
	# GET /attribute_groups/1.json
	def show
		@attribute_group = AttributeGroup.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json	{ render json: @attribute_group }
		end
	end

	# GET /attribute_groups/new
	# GET /attribute_groups/new.json
	def new
		@attribute_group = AttributeGroup.new

		respond_to do |format|
			format.html # new.html.erb
			format.json	{ render json: @attribute_group }
		end
	end

	# GET /attribute_groups/1/edit
	def edit
		@attribute_group = AttributeGroup.find(params[:id])
	end

	# POST /attribute_groups
	# POST /attribute_groups.json
	def create
		@attribute_group = AttributeGroup.new(params[:attribute_group])

		respond_to do |format|
			if @attribute_group.save
				format.html { redirect_to attribute_groups_url, notice: 'Attribute Group was successfully created.' }
				format.json	{ render json: @attribute_group, status: :created, :location => @attribute_group }
			else
				format.html { render action: "new" }
				format.json	{ render json: @attribute_group.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /attribute_groups/1
	# PUT /attribute_groups/1.json
	def update
		@attribute_group = AttributeGroup.find(params[:id])

		respond_to do |format|
			if @attribute_group.update_attributes(params[:attribute_group])
				format.html { redirect_to attribute_groups_url, notice: 'Attribute Group was successfully updated.' }
				format.json	{ head :ok }
			else
				format.html { render action: "edit" }
				format.json	{ render json: @attribute_group.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /attribute_groups/1
	# DELETE /attribute_groups/1.json
	def destroy
		@attribute_group = AttributeGroup.find(params[:id])
		@attribute_group.destroy

		respond_to do |format|
			format.html { redirect_to attribute_groups_url }
			format.json	{ head :ok }
		end
	end
	
	# PUT /attribute_groups/:id/enable
	# PUT /attribute_groups/:id/enable.json
	def enable
		@attribute_group = AttributeGroup.find(params[:id])
		
		respond_to do |format|
			if @attribute_group.update_attribute(:enabled, true)
				format.html { redirect_to attribute_groups_url, notice: "Attribute Group Enabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to attribute_groups_url, notice: "There was an error enabling this Attribute Group" }
				format.json	{ render json: @attribute_group.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
	# PUT /attribute_groups/:id/disable
	# PUT /attribute_groups/:id/disable.json
	def disable
		@attribute_group = AttributeGroup.find(params[:id])
		
		respond_to do |format|
			if @attribute_group.update_attribute(:enabled, false)
				format.html { redirect_to attribute_groups_url, notice: "Attribute Group Disabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to attribute_groups_url, notice: "There was an error disabling this Attribute Group" }
				format.json	{ render json: @attribute_group.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
end

www/app/helpers/attribute_groups_helper.rb
module AttributeGroupsHelper
end

www/app/views/attribute_groups/_attribute_group.html.erb
<tr class="<%= cycle('odd', 'even') %>">
	<td><%= attribute_group.name %></td>
	<td><%= attribute_group.enabled ? 'yes' : 'no' %></td>
	<td>
		<%= link_to '[edit]', edit_attribute_group_path(attribute_group) %>&nbsp;
		<% if attribute_group.enabled %>
			<%= link_to('[disable]', disable_attribute_group_url(attribute_group.id), :method => :put) %>
		<% else %>
			<%= link_to('[enable]', enable_attribute_group_url(attribute_group.id), :method => :put) %>&nbsp;
			<%= link_to '[delete]', attribute_group, :method => :delete, :confirm => "Are you sure you want to permanently delete this Attribute Group from the database?\n\nThis cannot be undone." %>
		<% end %>
	</td>
</tr>

www/app/views/attribute_groups/_form.html.erb
<%= form_for(@attribute_group) do |f| %>
	
	<% if @attribute_group.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@attribute_group.errors.count, "error") %> prohibited this Attribute Group from being saved:</h2>

			<ul>
			<% @attribute_group.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>
	
<% end %>

www/app/views/attribute_groups/edit.html.erb
<% content_for :header do %>
	<h3>Edit Attribute Group</h3>
<% end %>

<%= render 'form' %>

<div class="actions">
	<%= link_to 'Back', attribute_groups_path, :class => "make-button" %>
</div>

www/app/views/attribute_groups/index.html.erb
<% content_for :header do %>
	<h3>Attribute Groups</h3>
<% end %>

<table id="attribute_groups">
	<thead>
		<tr>
			<th>Name</th>
			<th>Enabled?</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => "attribute_group", :collection => @attribute_groups %>
	</tbody>
</table>

<div class="actions">
	<%= link_to "new attribute group", new_attribute_group_path, :class => "make-button" %>
</div>

www/app/views/attribute_groups/new.html.erb
<% content_for :header do %>
	<h3>New Attribute Group</h3>
<% end %>

<%= render 'form' %>

<div class="actions">
	<%= link_to 'Back', attribute_groups_path, :class => "make-button" %>
</div>