www/config/routes.rb
DealmylifeCom::Application.routes.draw do
  
  match "auth/:provider/callback" => "authentications#create"
  match "account/login" => "account#login", :as => :login
  match "account/logout" => "account#logout", :as => :logout
  match "account/reset_password" => "account#reset_password", :as => :reset_password
  match "click" => "clicks#new"
  
  resources :authentications
  
    resources :users, :except => [ :show, :new_user ] do
      
      put :enable, :on => :member
      put :disable, :on => :member
      
      match "roles" => "roles#index"
      put "role" => "roles#update"
      delete "role" => "roles#destroy"
      
      match "widgets" => "widgets#list"
      put "widget" => "widgets#assign"
      delete "widget" => "widgets#remove"
      
      match "categories" => "user_categories#index"
      put "category" => "user_categories#update"
      delete "category" => "user_categories#destroy"
      
    end
  
  resources :profiles, :except => [:new, :create] do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  namespace :profile do
    resources :addresses, :controller => "profile_addresses" do
      put :default, :on => :member
    end
  end
  

  resources :partners do
    put :enable, :on => :member
    put :disable, :on => :member
    
    resources :partner_categories, :controller => "partner_categories", :path => :categories, :as => :categories
    
  end

  
=begin
  resources :attribute_groups do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :attributes do
    put :enable, :on => :member
    put :disable, :on => :member
  end
=end
  
  resources :widgets do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :pages do
    put :enable, :on => :member
    put :disable, :on => :member
  end

  resources :categories
  
  match "partners/:id/updatefile" => "partners#updatefile", :as => :updatefile
  
  match "account/edit" => "users#edit", :as => :edit_account
  match "profile/edit" => "profiles#edit", :as => :edit_profile
  match "profile" => "profiles#show", :as => :show_profile
  
  match "page/:permalink" => "pages#show_by_permalink", :as => :permalink
  
  match ":controller(/:action(/:id))"
  

  root :to => "partners#show_all", :as => :index

end

www/app/models/partner.rb
class Partner < ActiveRecord::Base
  
  validates_uniqueness_of :name, :case_sensitive => false
  
  has_many :partner_categories, :dependent => :destroy
  has_many :categories, :through => :partner_categories
  
  def file
    SystemFile.new( File.join("lib", "assets", "partners"), name.downcase + ".rb" )
  end
  
  def get_deals ( address )
    load "#{Rails.root}/lib/assets/partners/" + name.downcase.gsub(" ", "-") + ".rb"
    #extend Api
    
    a = Api::Deals.new(self, address)
    a.get_deals
    return a.deals
    
    #return Api.get_deals(url, key, address)
  end
  
  def get_raw_data ( address )
    load "#{Rails.root}/lib/assets/partners/" + name.downcase.gsub(" ", "-") + ".rb"
    #extend Api
    
    a = Api::Deals.new(self, address)
    a.get_raw_data
    return a.deals
    
    #return Api.get_raw_data(url, key, address)
  end
  
end

module JSON
  def self.validate_and_parse json_
    return JSON.parse json_
  rescue JSON::ParserError  
    return false  
  end
end

module REXML
  def self.validate_and_parse xml_
    return REXML::Document.new xml_
  rescue REXML::ParseException  
    return false  
  end
end

www/app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_filter :check_developer_role, :except => [ :show, :show_all ]
  before_filter :set_cache_buster
  
  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render json: @partners }
    end
  end
  
  def show_all
    @partner = Partner.find_all_by_enabled(true)
    @marquee = "logo_md.png"
    @default_widgets = ["categories"]
    @categories = Category.select("id, name, ifnull(master_category_id, id) as master_category_id").order(:master_category_id, 1)
    
    ### if user enters a text address
    if params[:change_location] && params[:a] && !params[:a].empty?
      
      new_address = Address.new
      new_address = new_address.geocode params[:a]
      
    elsif logged_in_user
      
      ### if user selects saved address from dropdown
      if params[:pa_id]
        new_address = logged_in_user.profile.profile_addresses.find_by_id(params[:pa_id]).address
        
      elsif session[:address].nil?
        
        ### if user has a saved default address
        if logged_in_user.profile.addresses.length > 0
          new_address = logged_in_user.profile.addresses.all[0] # SHOULD GET DEFAULT ADDRESS HERE
          
        else
          new_address = Address.new
          new_address = new_address.geocode request.env["REMOTE_ADDR"].to_s
          
        end
        
      end
      
    end
    
    if !new_address.nil? && new_address.id != ( session[:address].try(:id) || 0 )
      session[:deals] = []
      session[:address] = new_address
      @partner.each do | partner |
        session[:deals] += partner.get_deals session[:address]
      end
    end
    
    unless session[:deals].nil?
      
      @total_items = session[:deals].length
      @page = [params[:p].to_i, 1].max
      @items_per_page = [params[:i].to_i, 5].max
      @total_pages = (@total_items / @items_per_page).ceil + 1
      @from = (@page * @items_per_page) - @items_per_page
      @to = @page * @items_per_page - 1
      
      if params[:s] && !params[:s].empty?
        @page = 1
        @items_per_page = 5
        @sort = params[:s].split(",")[0] || "remaining"
        @dir = params[:s].split(",")[1] || "asc"
        if @dir == "asc" then
          session[:deals].sort! do |a,b| a[@sort.to_sym] <=> b[@sort.to_sym] end
          #session[:deals].sort! do |a| a[@sort.to_sym] end
        elsif @dir == "desc" then
          session[:deals].sort! do |a,b| b[@sort.to_sym] <=> a[@sort.to_sym] end
          #session[:deals].sort! do |a| a[@sort.to_sym] end
        end
      end
      
    end
    
    respond_to do |format|
      if session[:address]
        @deals = session[:deals][@from..@to]
        #render :show <== WHY DOESN'T THIS WORK???  Want to share template.
        format.html # show_all.html.erb
        format.json  { render json: @partner }
      elsif logged_in_user
        notice = if flash[:notice] then flash[:notice] + " " else "" end
        format.html { redirect_to new_profile_address_path, notice: notice + "Please provide us with an address." }
      else
        format.html { redirect_to new_user_path }
      end
    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @partner = Partner.find params[:id]
    @marquee = "logo_md.png"
    @default_widgets = ["categories"]
    @categories = Category.select("id, name, ifnull(master_category_id, id) as master_category_id").order(:master_category_id, 1)
    
    ### if user enters a text address
    if params[:a] && !params[:a].empty?
      
      new_address = Address.new
      new_address = new_address.geocode params[:a]
      
    elsif logged_in_user
      
      ### if user selects saved address from dropdown
      if params[:pa_id] && params[:pa_id] != ( session[:address].try(:id) || 0 )
        new_address = logged_in_user.profile.profile_addresses.find_by_id(params[:pa_id]).address
        
      elsif session[:address].nil?
        
        ### if user has a saved default address
        if !logged_in_user.profile.nil?
          new_address = logged_in_user.profile.addresses.all[0]#.try(:to_s) SHOULD GET DEFAULT ADDRESS HERE
          
        else
          new_address = Address.new
          new_address = new_address.geocode request.env["REMOTE_ADDR"].to_s
          
        end
        
      end
      
    end
    
    if params[:test]
      @rawdata = @partner.get_raw_data session[:address] = new_address
    else
      session[:deals] = []
      session[:deals] += @partner.get_deals session[:address] = new_address
    end
    
    unless session[:deals].nil?
      
      @total_items = session[:deals].length
      @page = [params[:p].to_i, 1].max
      @items_per_page = [params[:i].to_i, 5].max
      @total_pages = (@total_items / @items_per_page).ceil + 1
      @from = (@page * @items_per_page) - @items_per_page + 1
      @to = @page * @items_per_page
      
      if params[:s] && !params[:s].empty?
        @page = 1
        @items_per_page = 5
        @sort = params[:s].split(",")[0] || "remaining"
        @dir = params[:s].split(",")[1] || "asc"
        if @dir == "asc" then
          session[:deals].sort! { |a,b| a[@sort.to_sym] <=> b[@sort.to_sym] }
        elsif @dir == "desc" then
          session[:deals].sort! { |a,b| b[@sort.to_sym] <=> a[@sort.to_sym] }
        end
      end
      
    end
    
    respond_to do |format|
      if session[:address]
        @deals = session[:deals][@from..@to]
        #render :show <== WHY DOESN'T THIS WORK???  Want to share template.
        format.html # show_all.html.erb
        format.json  { render json: @partner }
      elsif logged_in_user
        notice = if flash[:notice] then flash[:notice] + " " else "" end
        format.html { redirect_to new_profile_address_path, notice: notice + "Please provide us with an address." }
      else
        format.html { redirect_to new_user_path }
      end
    end
  end

  # GET /partners/new
  # GET /partners/new.json
  def new
    @partner = Partner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render json: @partner }
    end
  end

  # GET /partners/1/edit
  def edit
    @partner = Partner.find(params[:id])
    @file = @partner.file
  end
  
  # PUT /partners/1/updatefile
  def updatefile
    @partner = Partner.find(params[:id])
    
    respond_to do |format|
      if @partner.file.save(params[:content])
        format.html { redirect_to edit_partner_url, notice: "Partner Template File was successfully updated." }
        format.json  { head :ok }
      else
        format.html { render action: "edit" }
        format.json  { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(params[:partner])

    respond_to do |format|
      if @partner.save
        format.html { redirect_to partners_url, notice: "Partner was successfully created."  }
        format.json  { render json: @partner, status: :created, :location => @partner }
      else
        format.html { render action: "new" }
        format.json  { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /partners/1
  # PUT /partners/1.json
  def update
    @partner = Partner.find(params[:id])

    respond_to do |format|
      if @partner.update_attributes(params[:partner])
        format.html { redirect_to partners_url, notice: "Partner was successfully updated." }
        format.json  { head :ok }
      else
        format.html { render action: "edit" }
        format.json  { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url }
      format.json  { head :ok }
    end
  end
  
  # PUT /partners/:id/enable
  # PUT /partners/:id/enable.json
  def enable
    @partner = Partner.find(params[:id])
    
    respond_to do |format|
      if @partner.update_attribute(:enabled, true)
        format.html { redirect_to partners_url, notice: "Partner Enabled" }
        format.json { head :ok }
      else
        format.html { redirect_to partners_url, notice: "There was an error enabling this Partner" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  # PUT /partners/:id/disable
  # PUT /partners/:id/disable.json
  def disable
    @partner = Partner.find(params[:id])
    
    respond_to do |format|
      if @partner.update_attribute(:enabled, false)
        format.html { redirect_to partners_url, notice: "Partner Disabled" }
        format.json { head :ok }
      else
        format.html { redirect_to partners_url, notice: "There was an error disabling this Partner" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
end

www/app/helpers/partners_helper.rb
module PartnersHelper
	
	def get_excerpt (string, count = 30)
		if string.length >= count
		  shortened = string[0, count]
			splitted = shortened.split(/\s/)
			words = splitted.length
			splitted[0, words-1].join(" ") + ' ...'
		else
			string
		end
	end
	
	def format_date date
	  date[5..6]+"/"+date[8..9]+"/"+date[0..3] if !date.nil? and date.length >= 10
	end
  
end

www/app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
	<% if @partner.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

			<ul>
			<% @partner.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :url %><br />
		<%= f.text_field :url %>
	</div>
	<div class="field">
		<%= f.label :url_test %><br />
		<%= f.text_field :url_test %>
	</div>
	<div class="field">
		<%= f.label :key %><br />
		<%= f.text_field :key %>
	</div>
	<div class="field">
		<%= f.label :key_test %><br />
		<%= f.text_field :key_test %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

www/app/views/partners/_pager.html.erb
<div class="pager">
	<ul>
		<li class="info">
			<span>page <%= @page %> of <%= @total_pages %></span>
		</li>
		<li class="navigate">
			<ul>
				<% if @page-1 > 0 %><li class="prev"><a href="/?p=<%= @page-1 %>&i=<%= @items_per_page %>"><span>back one</span></a></li><% end %>
				
				<% if @page-3 > 0 %><li><a href="/?p=<%= @page-3 %>&i=<%= @items_per_page %>"><span><%= @page-3 %></span></a></li><% end %>
				<% if @page-2 > 0 %><li><a href="/?p=<%= @page-2 %>&i=<%= @items_per_page %>"><span><%= @page-2 %></span></a></li><% end %>
				<% if @page-1 > 0 %><li><a href="/?p=<%= @page-1 %>&i=<%= @items_per_page %>"><span><%= @page-1 %></span></a></li><% end %>
				<li><span><%= @page %></span></li>
				<% if @page+1 <= @total_pages %><li><a href="/?p=<%= @page+1 %>&i=<%= @items_per_page %>"><span><%= @page+1 %></span></a></li><% end %>
				<% if @page+2 <= @total_pages %><li><a href="/?p=<%= @page+2 %>&i=<%= @items_per_page %>"><span><%= @page+2 %></span></a></li><% end %>
				<% if @page+3 <= @total_pages %><li><a href="/?p=<%= @page+3 %>&i=<%= @items_per_page %>"><span><%= @page+3 %></span></a></li><% end %>
				
				<% if @page+1 <= @total_pages %><li class="next"><a href="/?p=<%= @page+1 %>&i=<%= @items_per_page %>"><span>more deals</span></a></li><% end %>
			</ul>
		</li>
		<li class="items">
			items / page: <a href="/?p=1&i=10"><span>10</span></a>&nbsp;<a href="/?p=1&i=25"><span>25</span></a>&nbsp;<a href="/?p=1&i=50"><span>50</span></a>
		</li>
	</ul>
</div>

www/app/views/partners/_partner.html.erb
<tr class="<%= cycle('odd', 'even') %>">
	<td><%= partner.name %></td>
	<td><%= partner.enabled ? 'yes' : 'no' %></td>
	<td>
		<%= link_to '[show]', partner %>&nbsp;
		<%= link_to '[edit]', edit_partner_path(partner) %>&nbsp;
		<% if partner.enabled %>
			<%= link_to('[disable]', disable_partner_url(partner.id), :method => :put) %>
		<% else %>
			<%= link_to('[enable]', enable_partner_url(partner.id), :method => :put) %>&nbsp;
			<%= link_to '[delete]', partner, :method => :delete, :confirm => "Are you sure you want to permanently delete this partner from the database?\n\nThis cannot be undone." %>
		<% end %>
	</td>
</tr>

www/app/views/partners/edit.html.erb
<% content_for :header do %>
	<h3>Edit Partner</h3>
<% end %>

<ul class="options">
	<li><%= link_to "Edit Partner Categories", partner_categories_path(@partner) %></li>
	<li><%= render "system_files/edit" %></li>
</ul>

<%= render "form" %>

<div class="actions">
	<%= link_to "Cancel", partners_path, :class => "make-button" %>
	<%= link_to "Show", @partner, :class => "make-button" %>
</div>

www/app/views/partners/index.html.erb
<% content_for :header do %>
	<h3>Partners</h3>
<% end %>

<table id="partners">
	<thead>
		<tr>
			<th>Name</th>
			<th>Enabled?</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => "partner", :collection => @partners %>
	</tbody>
</table>

<div class="actions">
	<%= link_to "new partner", new_partner_path, :class => "make-button" %>
</div>

www/app/views/partners/new.html.erb
<% content_for :header do %>
	<h3>New Partner</h3>
<% end %>

<%= render 'form' %>

<div class="actions">
	<%= link_to "Cancel", partners_path, :class => "make-button" %>
</div>

www/app/views/partners/show.html.erb
<% content_for :header do %>
	<% if !@deals.nil? %>
		<h3>Sort By: <%= @addr %></h3>
		<ul class="sort">
			<li><a href="/?s=sold,<%= if @sort == "sold" then if @dir == "asc" then "desc" else "asc" end else "desc" end %>"># Sold</a></li>
			<li><a href="/?s=remaining,<%= if @sort == "remaining" then if @dir == "asc" then "desc" else "asc" end else "asc" end %>">Time Left</a></li>
			<li><a href="/?s=value,<%= if @sort == "value" then if @dir == "asc" then "desc" else "asc" end else "asc" end %>">Original Price</a></li>
			<li><a href="/?s=discountPercent,<%= if @sort == "discountPercent" then if @dir == "asc" then "desc" else "asc" end else "desc" end %>">% Discount</a></li>
			<li><a href="/?s=discountAmount,<%= if @sort == "discountAmount" then if @dir == "asc" then "desc" else "asc" end else "desc" end %>">$ Savings</a></li>
			<li><a href="/?s=price,<%= if @sort == "price" then if @dir == "asc" then "desc" else "asc" end else "asc" end %>">Deal Price</a></li>
		</ul>
	<% end %>
<% end %>

<div id="deals">
	
	<div class="header">
		<div class="location">Deals near: <%= session[:address].to_s %></div>
	
	<% if @rawdata %>
		
			<div class="rawdata"><%= @rawdata %></div>
		</div>
		
	<% elsif @deals %>
		
			<%= render :partial => "pager" %>
		</div>
		
		<ul class="deals">
		<% @deals.each do | deal | %>
			<li id="<%= deal[:id] %>" <% unless deal[:category].nil? or logged_in_user.nil? or (!logged_in_user.nil? and logged_in_user.has_category? deal[:categoryId]) %>class="hide"<% end %>class="zoom">
				<div class="left-col">
					<table class="layout">
						<tr>
							<td width="220px">
								<div class="image"><img src="<%= deal[:imageUrl] %>" width="200px" /></div>
							</td>
							<td class="center">
								<!--<div class="title"><a href="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>" target="_blank"><h4><%= deal[:title] %></h4></a></div>-->
								<div class="title" rel="zoom"><h4><%= deal[:title] %></h4></div>
								<div class="value">
									<ul>
										<li>Discount: <%= deal[:discountPercent] %>%</li>
										<li>Savings: <%= number_to_currency(deal[:discountAmount]/100) %></li>
									</ul>
								</div>
							</td>
						</tr>
					</table>
				</div>	
				
				<div class="right-col">
					<table>
						<tr><td>
							<p class="original"><%= number_to_currency(deal[:value]/100) %></p>
							<p class="price"><%= number_to_currency(deal[:price]/100) %></p>
						</td></tr>
						<tr><td>
							<span class="grab"><a href="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) + "&partner=" + deal[:partner_id].to_s %>" class="make-button" target="_blank">Grab</a></span>
						</td></tr>
						<tr><td>
							<span class="share">
								<ul>
									<!--<li>Share:</li>-->
									<li>
										<!-- AddThis Button BEGIN -->
										<div class="social-links addthis_toolbox addthis_default_style">
											<ul>
												<!--<li><a class="addthis_button_print"></a></li>-->
												<li><a class="addthis_button_email" addthis:url="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>"></a></li>
												<li><a class="addthis_button_facebook" addthis:url="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>"></a></li>
												<li><a class="addthis_button_twitter" addthis:url="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>"></a></li>
												<li><a class="addthis_button_google_plusone_share" addthis:url="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>"></a></li>
												<li><a class="addthis_button_pinterest_share" addthis:url="<%= click_url + "?redirect=" + url_encode(deal[:dealUrl]) %>"></a></li>
											</ul>
										</div>
										<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-501612275c2a20e5"></script>
										<!-- AddThis Button END -->
									</li>
									<!--
									<li><a href="http://www.facebook.com/share.php?u=<%= @url %>" target="_blank"><span>f</span></a></li>
									<li><a href="http://twitter.com/home/?status=DealMyLife.com : <%= @url %>" target="_blank"><span>t</span></a></li>
									-->
								</ul>
							</span>
						</td></tr>
					</table>
				</div>
				
				<div class="bottom">
					<table class="details">
						<tr><td><dt>Deal brought to you by:</dt><dd><%= deal[:partner] %></dd></td></tr>
						<tr>
							<td>
								<% unless deal[:category].nil? %>
									<dt>Category:</dt><dd id="<%= deal[:categoryId] %>" class="category-id"><%= deal[:category] %></dd>
								<% end %>
							</td>
						</tr>
						<tr>
							<td>
								<% unless deal[:locations].nil? or deal[:locations].length == 0 or deal[:locations][0][:neighborhood].nil? or deal[:locations][0][:neighborhood].length == 0 %>
									<dt>Where to find Deal:</dt>
									<dd>
										<% if deal[:locations].length > 2 %>
											Multiple Locations
										<% else %>
											<% deal[:locations].each_with_index do | location, i | %>
												<%= "- " if i != 0 && location[:neighborhood] != "" %><%= location[:neighborhood] %>
											<% end %>
										<% end %>
									</dd>
								<% end %>
							</td>
						</tr>
					</table>
					<table class="details">
						<tr>
							<td>
								<% # unless deal[:begin].nil? or deal[:begin].length == 0 %>
									<dt>Discovered:</dt><dd><%= format_date deal[:begin] %></dd>
								<% # end %>
							</td>
						</tr>
						<tr>
							<td>
								<% unless deal[:remaining] <= 0 %>
									<dt>Time Left:</dt><dd><%= deal[:remaining] %> days</dd>
								<% else %>
									<dt>Time Left:</dt><dd>Expiring Soon!</dd>
								<% end %>
							</td>
						</tr>
						<tr>
							<td>
								<% unless deal[:sold].nil? %>
									<dt>Deals Sold:</dt><dd><%= deal[:sold] %></dd>
								<% end %>
							</td>
						</tr>
					</table>
					<div class="clear"></div>
				</div>
				
				<!--<button class="make-button show-pitch">More Info</button>-->
				<div class="pitch">
					<p><%= raw deal[:description] %></p>
					<div class="highlights"><p><%= raw deal[:highlightsHtml] %></p></div>
					<p><%= raw deal[:pitchHtml] %></p>
				</div>
				
				<!-- debug -->
				<div class="hide">
					<% deal.each do |key, value| %>
						<span><b><%=h "#{key.to_s}" %>: </b><%=h "#{value.to_s}" %></span><br /><br />
					<% end %>
				</div>
				
			</li>
		<% end %>
		</ul>
		<div class="footer">
			<%= render :partial => "pager" %>
		</div>
	
		<script>
			
			jQuery(document).ready(function() {
				
				jQuery(".zoom").zoom();
				
				jQuery(".portlet-header .sort li a").addClass("radius-10 asc");
				jQuery(this).find("#deals .show-pitch").click(function() {
					if (jQuery(this).hasClass("visible")) {
						jQuery(this).removeClass("visible").siblings(".pitch").slideUp();
					} else {
						jQuery(this).addClass("visible").siblings(".pitch").slideDown();
					}
				});
				
			});
			
			jQuery(window).load(function() {
				
				jQuery("#side_left, #body_top .portlet-header").noScroll();
				
			});
	
		</script>
		
	<% else %>
		
		<p>We're sorry, no deals were found near the address you provided.</p>
		<p>Check the spelling of the City you entered, or try searching for deals in a larger, nearby city.</p>
	
	<% end %>

</div>

www/app/views/partners/test.html.erb
<h1>this is a test</h1>