www/config/routes.rb
DealmylifeCom::Application.routes.draw do
  
  match "auth/:provider/callback" => "authentications#create"
  match "account/login" => "account#login", :as => :login
  match "account/logout" => "account#logout", :as => :logout
  match "account/reset_password" => "account#reset_password", :as => :reset_password
  match "click" => "clicks#new"
  
  resources :authentications
  
    resources :users, :except => [ :show, :new_user ] do
      
      put :enable, :on => :member
      put :disable, :on => :member
      
      match "roles" => "roles#index"
      put "role" => "roles#update"
      delete "role" => "roles#destroy"
      
      match "widgets" => "widgets#list"
      put "widget" => "widgets#assign"
      delete "widget" => "widgets#remove"
      
      match "categories" => "user_categories#index"
      put "category" => "user_categories#update"
      delete "category" => "user_categories#destroy"
      
    end
  
  resources :profiles, :except => [:new, :create] do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  namespace :profile do
    resources :addresses, :controller => "profile_addresses" do
      put :default, :on => :member
    end
  end
  

  resources :partners do
    put :enable, :on => :member
    put :disable, :on => :member
    
    resources :partner_categories, :controller => "partner_categories", :path => :categories, :as => :categories
    
  end

  
=begin
  resources :attribute_groups do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :attributes do
    put :enable, :on => :member
    put :disable, :on => :member
  end
=end
  
  resources :widgets do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :pages do
    put :enable, :on => :member
    put :disable, :on => :member
  end

  resources :categories
  
  match "partners/:id/updatefile" => "partners#updatefile", :as => :updatefile
  
  match "account/edit" => "users#edit", :as => :edit_account
  match "profile/edit" => "profiles#edit", :as => :edit_profile
  match "profile" => "profiles#show", :as => :show_profile
  
  match "page/:permalink" => "pages#show_by_permalink", :as => :permalink
  
  match ":controller(/:action(/:id))"
  

  root :to => "partners#show_all", :as => :index

end

www/app/models/widget.rb
class Widget < ActiveRecord::Base
	attr_protected :enabled
	
	validates_presence_of :name
	validates_presence_of :title
	
	validates_length_of :name, :within => 3..64
	validates_length_of :title, :within => 3..64
	validates_length_of :head, :maximum => 1000
	validates_length_of :content, :maximum => 1000
	
	has_many :user_widgets
	has_many :users, :through => :user_widgets
end

www/app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
	before_filter :check_developer_role, :except => [ :list, :assign, :remove ]
	before_filter :login_required
	
	# GET /widgets
	# GET /widgets.json
	def index
		@widgets = Widget.all

		respond_to do |format|
			format.html # index.html.erb
			format.json	{ render json: @widgets }
		end
	end

	# GET /widgets/:id
	# GET /widgets/:id.json
	def show
		@widget = Widget.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json	{ render json: @widget }
		end
	end

	# GET /widgets/new
	# GET /widgets/new.json
	def new
		@widget = Widget.new

		respond_to do |format|
			format.html # new.html.erb
			format.json	{ render json: @widget }
		end
	end

	# GET /widgets/1/edit
	def edit
		@widget = Widget.find(params[:id])
	end

	# POST /widgets
	# POST /widgets.json
	def create
		@widget = Widget.new(params[:widget])

		respond_to do |format|
			if @widget.save
				format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
				format.json	{ render json: @widget, status: :created, :location => @widget }
			else
				format.html { render action: "new" }
				format.json	{ render json: @widget.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /widgets/:id
	# PUT /widgets/:id.json
	def update
		@widget = Widget.find(params[:id])

		respond_to do |format|
			if @widget.update_attributes(params[:widget])
				format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
				format.json	{ head :ok }
			else
				format.html { render action: "edit" }
				format.json	{ render json: @widget.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /widgets/:id
	# DELETE /widgets/:id.json
	def destroy
		@widget = Widget.find(params[:id])
		@widget.destroy

		respond_to do |format|
			format.html { redirect_to widgets_url }
			format.json	{ head :ok }
		end
	end
	
	# PUT /widgets/:id/enable
	# PUT /widgets/:id/enable.json
	def enable
		@widget = Widget.find(params[:id])
		
		respond_to do |format|
			if @widget.update_attribute(:enabled, true)
				format.html { redirect_to widgets_url, notice: "Widget Enabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to widgets_url, notice: "There was an error enabling this Widget" }
				format.json	{ render json: @widget.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
	# PUT /widgets/:id/disable
	# PUT /widgets/:id/disable.json
	def disable
		@widget = Widget.find(params[:id])
		
		respond_to do |format|
			if @widget.update_attribute(:enabled, false)
				format.html { redirect_to widgets_url, notice: "Widget Disabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to widgets_url, notice: "There was an error disabling this Widget" }
				format.json	{ render json: @widget.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
	# GET /users/:user_id/widgets
	# GET /users/:user_id/widgets.json
	def list
		@widgets = Widget.find_all_by_enabled(true)
		@user = User.find(params[:user_id])

		respond_to do |format|
			format.html { render action: "index" }
			format.json	{ render json: @widgets }
		end
	end
	
	# PUT /users/:user_id/widget?id=:id
	def assign
		@widget = Widget.find(params[:id])
		@user = User.find(params[:user_id])
		
		container = if params[:container] then params[:container] else "side_left" end
		order = if params[:order] then params[:order] else 1000 end
		
		if @user.has_widget?(@widget.name)
			@user.widgets.delete(@widget)
		end
		
		if @widget.enabled
			#@user.widgets << @widget	# I don't think this method of assignment works due to the extra parameters in the lookup table. Use UserWidget.create() instead.
			UserWidget.create(:user => @user, :widget => @widget, :container => container, :order => order)
		end
		
		respond_to do |format|
			format.html { redirect_to user_widgets_url, notice: "Widget was successfully added to user profile." }
		end
	end
	
	# DELETE /users/:user_id/widget?id=:id
	def remove
		@widget = Widget.find(params[:id])
		@user = User.find(params[:user_id])
		if @user.has_widget?(@widget.name)
			@user.widgets.delete(@widget)
		end
		
		respond_to do |format|
			format.html { redirect_to user_widgets_url, notice: "Widget was successfully removed from user profile." }
		end
	end
	
end

www/app/helpers/widgets_helper.rb
module WidgetsHelper
end

www/app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
	<% if @widget.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

			<ul>
			<% @widget.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :head %><br />
		<%= f.text_area :head %>
	</div>
	<div class="field">
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</div>
	<div class="field">
		<%= f.label :enabled %><br />
		<%= f.check_box :enabled %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

www/app/views/widgets/_widget.html.erb
<tr class="<%= cycle('odd', 'even') %>">
	<td><%= widget.name %></td>
	<td><%= widget.title %></td>
	<% if @user %>
		<td>
			<% if @user.has_widget?(widget.name) %>
				<%= link_to '[remove widget]', user_widget_url(:id => widget.id, :user_id => @user.id), :method => :delete, :confirm => "Are you sure you want to revoke this widget?." %>
			<% else %>
				<%= link_to '[assign widget]', user_widget_url(:id => widget.id, :user_id => @user.id), :method => :put %>
			<% end %>
		</td>
	<% else %>
		<td><%= widget.enabled ? 'yes' : 'no' %></td>
		<td>
			<%= link_to '[show]', widget %>&nbsp;
			<%= link_to '[edit]', edit_widget_path(widget) %>&nbsp;
			<%= link_to '[delete]', widget, :confirm => 'Are you sure?', :method => :delete %>
			<% if widget.enabled %>
				<%= link_to('[disable]', disable_widget_url(widget.id), :method => :put) %>
			<% else %>
				<%= link_to('[enable]', enable_widget_url(widget.id), :method => :put) %>&nbsp;
				<%= link_to '[delete]', widget, :method => :delete, :confirm => "Are you sure you want to permanently delete this Widget from the database?\n\nThis cannot be undone." %>
			<% end %>
		</td>
	<% end %>
</tr>

www/app/views/widgets/edit.html.erb
<% content_for :header do %>
	<h3>Edit Widget</h3>
<% end %>

<%= render "form" %>

<div class="actions">
	<%= link_to "Back", widgets_path, :class => "make-button" %>
	<%= link_to "Show", @widget, :class => "make-button" %>
</div>

www/app/views/widgets/index.html.erb
<% content_for :header do %>
	<h3>Widgets <%= if @user then "for user: " + @user.email end %></h3>
<% end %>

<table id="widgets">
	<thead>
		<tr>
			<th>Name</th>
			<td>Title</td>
			<% if @user.nil? %>
				<th>Enabled?</th>
			<% end %>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => "widget", :collection => @widgets %>
	</tbody>
</table>

<% if @user.nil? %>
	<div class="actions">
		<%= link_to "new widget", new_widget_path, :class => "make-button" %>
	</div>
<% end %>

www/app/views/widgets/new.html.erb
<% content_for :header do %>
	<h3>New Widget</h3>
<% end %>

<%= render "form" %>

<div class="actions">
	<%= link_to "Back", widgets_path, :class => "make-button" %>
</div>

www/app/views/widgets/show.html.erb
<% content_for :header do %>
	<h3>Widget: <%= @widget.name %></h3>
<% end %>

<p>
	<b>Title:</b>
	<%= @widget.title %>
</p>

<p>
	<b>Head:</b>
	<%= @widget.head %>
</p>

<p>
	<b>Content:</b>
	<%= @widget.content %>
</p>

<p>
	<b>Enabled:</b>
	<%= @widget.enabled %>
</p>

<div class="actions">
	<%= link_to "Edit", edit_widget_path(@widget), :class => "make-button" %>
	<%= link_to "Back", widgets_path, :class => "make-button" %>
</div>