www/config/routes.rb
DealmylifeCom::Application.routes.draw do
  
  match "auth/:provider/callback" => "authentications#create"
  match "account/login" => "account#login", :as => :login
  match "account/logout" => "account#logout", :as => :logout
  match "account/reset_password" => "account#reset_password", :as => :reset_password
  match "click" => "clicks#new"
  
  resources :authentications
  
    resources :users, :except => [ :show, :new_user ] do
      
      put :enable, :on => :member
      put :disable, :on => :member
      
      match "roles" => "roles#index"
      put "role" => "roles#update"
      delete "role" => "roles#destroy"
      
      match "widgets" => "widgets#list"
      put "widget" => "widgets#assign"
      delete "widget" => "widgets#remove"
      
      match "categories" => "user_categories#index"
      put "category" => "user_categories#update"
      delete "category" => "user_categories#destroy"
      
    end
  
  resources :profiles, :except => [:new, :create] do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  namespace :profile do
    resources :addresses, :controller => "profile_addresses" do
      put :default, :on => :member
    end
  end
  

  resources :partners do
    put :enable, :on => :member
    put :disable, :on => :member
    
    resources :partner_categories, :controller => "partner_categories", :path => :categories, :as => :categories
    
  end

  
=begin
  resources :attribute_groups do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :attributes do
    put :enable, :on => :member
    put :disable, :on => :member
  end
=end
  
  resources :widgets do
    put :enable, :on => :member
    put :disable, :on => :member
  end
  
  resources :pages do
    put :enable, :on => :member
    put :disable, :on => :member
  end

  resources :categories
  
  match "partners/:id/updatefile" => "partners#updatefile", :as => :updatefile
  
  match "account/edit" => "users#edit", :as => :edit_account
  match "profile/edit" => "profiles#edit", :as => :edit_profile
  match "profile" => "profiles#show", :as => :show_profile
  
  match "page/:permalink" => "pages#show_by_permalink", :as => :permalink
  
  match ":controller(/:action(/:id))"
  

  root :to => "partners#show_all", :as => :index

end

www/app/models/user.rb
require 'digest/sha2'
require 'securerandom'

class User < ActiveRecord::Base
  
	attr_protected :hashed_password, :enabled
	attr_accessor :password, :remember_me

	validates_presence_of :email
	validates_presence_of :password, :if => :password_required?
	validates_presence_of :password_confirmation, :if => :password_required?

	validates_confirmation_of :password, :if => :password_required?
	
	validates_uniqueness_of :email, :case_sensitive => false
	
	validates_length_of :email, :within => 5..128
	validates_length_of :password, :within => 6..20, :if => :password_required?
	
	has_many  :authentications, :dependent => :destroy
	
	has_many	:user_roles, :dependent => :destroy
	has_many	:roles, :through => :user_roles
	
	has_many	:user_widgets, :dependent => :destroy
	has_many	:widgets, :through => :user_widgets
  
  has_many  :user_categories, :dependent => :destroy
  has_many  :categories, :through => :user_categories
	
	has_one		:profile, :dependent => :destroy
	
	has_many  :clicks
	
	#acts_as_mappable
	
	before_save :hash_password
	def hash_password
		self.hashed_password = User.encrypt(password) if !password.blank?
	end

	def password_required?
		(hashed_password.blank? && authentications.empty?) || !password.blank?
	end
	
	def reset_password
    random_string = SecureRandom.hex(8)
    self.hashed_password = User.encrypt random_string
    self.save
    return random_string
  end

	def self.encrypt(string)
		return Digest::SHA256.hexdigest(string)
	end
	
	def self.authenticate(email, password)
		find_by_email_and_hashed_password_and_enabled(email, User.encrypt(password), true)
	end
	
	def has_role?(rolename)
		self.roles.find_by_name(rolename) ? true : false
	end
	
	def has_widget?(widgetname)
		self.widgets.find_by_name(widgetname) ? true : false
	end
  
  def has_category?(categoryid)
    self.categories.find_by_id(categoryid) ? true : false
  end
  
end

www/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :check_administrator_role, :only => [ :index, :destroy, :enable ]
	before_filter :login_required, :except => [ :new, :create ]
	
	# GET /users
	# GET /users.json
	def index
		@users = User.all

		respond_to do |format|
			format.html # index.html.erb
			format.json	{ render json: @users }
		end
	end

	# GET /users/1
	# GET /users/1.json
=begin
	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json	{ render json: @user }
		end
	end
=end

	# GET /users/new
	# GET /users/new.json
	def new
		@user = User.new
		@categories = Category.all
    @layout = "one-col"
    @marquee = "marquee_sm.png"

		respond_to do |format|
			format.html # new.html.erb
			format.json	{ render json: @user }
		end
	end

	# GET /users/1/edit or /users/:userid/edit
	def edit
		if params[:id]
			@user = User.find(params[:id])
		else
			@user = logged_in_user
		end
	end

	# POST /users
	# POST /users.json
	def create
		@user = User.new(params[:user])

		respond_to do |format|
			if @user.save
        #AccountMailer.welcome_email(@user).deliver
			  @user.profile ||= Profile.new
			  @user.profile.gender = params[:gender]
			  
			  UserMailer.welcome_email(@user).deliver
		    
		    if params[:a] && !params[:a].empty?
          address = Address.new
          address.geocode params[:a]
          profile_address = ProfileAddress.new :profile => @user.profile, :address => address, :label => "Default Address", :default => @user.profile.profile_addresses.count.to_i.zero?
          address.destroy unless !address.geocode.nil? and address.save and profile_address.save
        end
        
        if params[:categories]
  			  params[:categories].each do | name, id |
            if @category = Category.find_by_id(id)
              @user.categories << @category if !(@user.has_category?(@category.id))
            end
  			  end
  			else
          Category.all.each do | category |
            @user.categories << category if !(@user.has_category?(category.id))
          end
  			end
			  
			  if logged_in_user
          format.html { redirect_to users_url, notice: "Congratulations! User Account has been created." }
				  format.json	{ render json: @user, status: :created, :location => @user }
			  else
          self.logged_in_user = User.authenticate(params[:user][:email], params[:user][:password])
				  format.html { redirect_to index_url, notice: "Congratulations! Your User Account has been created. Welcome to DealMyLife.com!" }
			  end
			else
				format.html { render action: "new" }
				format.json	{ render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /users/1
	# PUT /users/1.json
	def update
		@user = User.find(params[:id])

		respond_to do |format|
			if @user.update_attributes(params[:user])
				#format.html { post_to :controller => "account", action: "logout", notice: "User Account has been updated." }
        format.html { redirect_to profile_url, notice: "Password has been successfully updated." }
				format.json	{ head :ok }
			else
				format.html { render action: "edit" }
				format.json	{ render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user = User.find(params[:id])
		@user.destroy

		respond_to do |format|
			format.html { redirect_to users_url }
			format.json	{ head :ok }
		end
	end
	
	# PUT /users/:id/enable
	# PUT /users/:id/enable.json
	def enable
		@user = User.find(params[:id])
		
		respond_to do |format|
			if @user.update_attribute(:enabled, true)
				format.html { redirect_to users_url, notice: "User Enabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to users_url, notice: "There was an error enabling this User" }
				format.json	{ render json: @user.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
	# PUT /users/:id/disable
	# PUT /users/:id/disable.json
	def disable
		@user = User.find(params[:id])
		
		respond_to do |format|
			if @user.update_attribute(:enabled, false)
				format.html { redirect_to users_url, notice: "User Disabled" }
				format.json	{ head :ok }
			else
				format.html { redirect_to users_url, notice: "There was an error disabling this User" }
				format.json	{ render json: @user.errors, status: :unprocessable_entity }
			end
		end
		
	end
	
end

www/app/helpers/users_helper.rb
module UsersHelper
end

www/app/views/users/_user.html.erb
<tr class="<%= cycle('odd', 'even') %>">
	<td><%= user.email %></td>
	<td><%= user.enabled ? 'yes' : 'no' %></td>
	<td>
		<%= link_to '[edit]', edit_user_url(user) %>&nbsp;
		<%= link_to '[roles]', user_roles_url(user.id) %>&nbsp;
		<% unless user == logged_in_user %>
			<% if user.enabled %>
				<%= link_to('[disable]', disable_user_url(user.id), :method => :put) %>
			<% else %>
				<%= link_to('[enable]', enable_user_url(user.id), :method => :put) %>&nbsp;
				<%= link_to '[delete]', user, :method => :delete, :confirm => "Are you sure you want to permanently delete this User from the database?\n\nThis cannot be undone." %>
			<% end %>
		<% end %>
	</td>
</tr>

www/app/views/users/_widget.html.erb
<ul>
	<li class="title">Account</li>
	<% if is_logged_in? %>
		<li><%= link_to 'Edit Profile', edit_profile_path %></li>
		<li><%= link_to "Update Password", edit_account_path %></li>
		<li><%= link_to "Addresses", profile_addresses_path %></li>
		<li><%= link_to 'Widgets', user_widgets_path(logged_in_user.id) %></li>
		<li><%= link_to 'Categories', user_categories_path(logged_in_user.id) %></li>
		<li><%= link_to 'Logout', logout_path, :method => :post %></li>
	<% else %>
		<li><%= link_to 'Register', :controller => 'users', :action => 'new' %></li>
		<li><%= link_to 'Login', :controller => 'account', :action => 'login' %></li>
	<% end %>					
</ul>

<% if logged_in_user and logged_in_user.has_role?('administrator') %>
	<ul>
		<li class="title">Admin Options</li>
		<li><%= link_to 'Edit Users', users_path %></li>
	</ul>	
<% end %>

<% if logged_in_user and logged_in_user.has_role?('developer') %>
	<ul>
		<li class="title">Developer Options</li>
		<li><%= link_to 'Edit Widgets', widgets_path %></li>
		<li><%= link_to 'Edit Partners', partners_path %></li>
		<li><%= link_to 'Edit Categories', categories_path %></li>
	</ul>	
<% end %>

<% if logged_in_user and logged_in_user.has_role?('editor') %>
	<ul>
		<li class="title">Editor Options</li>
		<li><%= link_to 'Edit Pages', pages_path %></li>	
	</ul>	
<% end %>

<% if logged_in_user and logged_in_user.has_role?('manager') %>
	<ul>
		<li class="title">Manager Options</li>
	</ul>	
<% end %>

<% if logged_in_user and logged_in_user.has_role?('partner') %>
	<ul>
		<li class="title">Partner Options</li>
	</ul>	
<% end %>

www/app/views/users/del.show.html.erb
<% content_for :header do %>
	<h3>User: <%= @user.email %></h3>
<% end %>

<p>Member since <%= @user.created_at.to_s(:long) %></p>

<% if logged_in_user == @user %>
	<div class="actions">
		<%= link_to "edit", edit_user_path(@user), :class => "make-button" %>
	</div>
<% end %>

www/app/views/users/edit.html.erb
<% content_for :header do %>
	<h3>Edit User: <%= @user.email %></h3>
<% end %>

<%= form_for :user, :url => user_path(@user), :html => { :method => :put } do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<% if logged_in_user and logged_in_user.has_role?('administrator') %>
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= submit_tag 'Save' %>
	</div>
<% end %>

<div class="actions">
	<%= link_to "Back", show_profile_path, :class => "make-button" %>
</div>

www/app/views/users/enable.html.erb
<% content_for :header do %>
	<h3>Users#enable</h3>
<% end %>

<p>Find me in app/views/users/enable.html.erb</p>

www/app/views/users/index.html.erb
<% content_for :header do %>
	<h3>Users</h3>
<% end %>

<table id="users">
	<thead>
		<tr>
			<th>Email</th>
			<th>Enabled?</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => "user", :collection => @users %>
	</tbody>
</table>

<div class="actions">
	<%= link_to "new user", new_user_path, :class => "make-button" %>
</div>

www/app/views/users/new.html.erb
<% content_for :header do %>
	<h3>All your local daily deals in one place, at one time, 50% - 90% off of life's great offers!</h3>
<% end %>
<div id="new_user">
	<%#= form_tag users_url, :method => "post" do %>
	<%= form_for :user, :url => users_path do |f| %>
		<%= hidden_field_tag(:change_location, "1") %>
		
		<!--<span class="login">Already signed up? <%= link_to 'Login Now', :controller => 'account', :action => 'login' %></span>-->
		<div class="scrollable">
			<div class="steps">
				
				<div class="step one">
					<table>
						<tr>
							<td class="pane" width="33%">
								<div class="social-logins">
									<%= render :partial => "account/social_logins" %>
								</div>
							</td>
							<td class="pane" width="66%">
								<div>
									<h4>We bring You over a thousand Deals a Day, and You will only see the ones You Like, for Free!</h4>
									<h1><label for="a">Where's your life?</label></h1>
									<%= text_field_tag :a, nil, :placeholder => "City, Zip, or Address..." %>
								</div>
								<div class="browse next"><span>next</span></div>
							</td>
							<!--
							<td width="33%">
								<div>
									<h1>What is DealMyLife.com?</h1>
									<iframe width="300" height="225" src="http://www.youtube.com/embed/Dt4zvJNXbdI" frameborder="0" allowfullscreen></iframe>
								</div>
							</td>
							-->
						</tr>
					</table>
				</div>
				
				<div class="step two">
					<table class="pane">
						<tr><td colspan="3">
							<h1>Sign Up. It's FREE!</h1>
							<div class="browse prev"><span>prev</span></div>
							<div class="browse next"><span>next</span></div>
						</td></tr>
						<tr>
							<td width="45%">
								<div class="social-logins">
									<%= render :partial => "account/social_logins" %>
								</div>
							</td>
							
							<td class="or" width="10%">
								<div>OR</div>
							</td>
							
							<td width="45%">
								<ul>
									<li><%= f.text_field :email, :placeholder => "email address" %></li>
									<li><%= f.password_field :password, :placeholder => "password" %></li>
									<li><%= f.password_field :password_confirmation, :placeholder => "confirm password" %></li>
								</ul>
							</td>
						</tr>
						<tr><td colspan="3"><h4>To create an account, you can either log in with Facebook, or enter a valid email address and password (must be at least 6 characters), and be sure to enter a matching confirmation password.</h4></td></tr>
						<tr><td colspan="3"><p>Your email is safe with us, we will never share it and use it only to send you the deals you want, for free!</p></td></tr>
						<tr><td colspan="3"><h2 class="find"><%= submit_tag "Skip and Find Deals!", :formaction => index_path %></h2></td></tr>
					</table>
				</div>
				
				<div class="step three">
					<table class="pane">
						<tr>
							<td>
								<h4>Lets save you some money on the deals you like..... Select your deals of interest, (you can always change this later)</h4>
								<p>I am a <%= select_tag :gender, options_for_select(['Rather not say', 'Male', 'Female']) %> and my life began in <%= select_year(Date.today, :start_year => 1930, :end_year => Date.today.year-18) %></p><br />
								<h4>What kind of Deals are you interested in?</h4>
								<table class="categories">
									<tr>
										<td colspan="3">
											<%= check_box_tag :all %><%= label_tag :all, "All Daily Deals!" %>
											<div class="browse prev"><span>prev</span></div>
										</td>
									</tr>
									<% if @categories %>
										<tr>
											<% @categories.each_with_index do |category, index| %>
												<td><%= check_box_tag "categories[#{category.name.downcase.gsub(/\W+/, '')}]", category.id, true, :id => "categories_#{category.name.downcase.gsub(/\W+/, '')}" %><%= label_tag "categories_#{category.name.downcase.gsub(/\W+/, '')}", "#{category.name}" %></td>
												<% if (index+1) % 3 == 0 %></tr><tr><% end %>
											<% end %>
										</tr>
									<% end %>
									<tr><td colspan="3"><%= check_box_tag :agree %><%= label_tag :agree, "I agree to the Terms and Conditions", :class => "agree" %></td></tr>
								</table>
								<div class="browse next find"><span>FIND!</span></div>
							</td>
						</tr>
					</table>
				</div>
				
			</div>
		</div>
		
	<% end %>
</div>

<script type="text/javascript">
	
	jQuery.fn.vert_center = function(params) {
		this.each(function() {
			var e = jQuery(this);
			var e_margin = ( 400 - e.outerHeight() ) / 2;
			e.css("margin-top", e_margin);
		});
	};
	
	jQuery.fn.validate = function(api) {
		var step = jQuery(this).parents(".step");
		if (api.getIndex() == 0) {
			if (step.find("#a").val().length > 4) {
				return true;
			}
		} else if (api.getIndex() == 1) {
			var complete = 0;
			var email = step.find("#user_email");
			var password = step.find("#user_password");
			var password_confirmation = step.find("#user_password_confirmation");
			if (password.val().length >= 8) {
				password.addClass("valid");
				complete++;
			} else {
				password.removeClass("valid");
			}
			if (password_confirmation.val().length >= 8 && password.val() == password_confirmation.val()) {
				password_confirmation.addClass("valid");
				complete++;
			} else {
				password_confirmation.removeClass("valid");
			}
			if (email.val().match(/^\s*[\w\-\+_]+(\.[\w\-\+_]+)*\@[\w\-\+_]+\.[\w\-\+_]+(\.[\w\-\+_]+)*\s*$/)) {
				email.addClass("valid");
				complete++;
			} else {
				email.removeClass("valid");
			}
			if (complete == 3) {
				return true;
			}
		} else if (api.getIndex() == 2) {
			if (step.find("#agree").attr("checked")) {
				return true;
			}
		}
		return false;
	};
	
	jQuery.fn.stealKeys = function(api) {
		var key = jQuery(this);
		key.keypress(function(e) {
			if (e.keyCode == 13) {
				var node = (e.target) ? e.target : ((e.srcElement) ? e.srcElement : null);
				if (key.validate(api)) {
					api.next();
				}
				e.preventDefault();
				return false;
			}
		});
	};
	
	jQuery(document).ready(function() {
		
		jQuery(".scrollable").scrollable({
			keyboard:false,
			prev:".prev span",
			next:".next span"
		});
		var api = jQuery(".scrollable").data("scrollable");
		
		//jQuery(".steps > div").vert_center();
		
		jQuery(".find").click(function() {
			jQuery(this).parents("form").submit();
		});
		
		jQuery("input[type=text], input[type=password], input[type=submit]").stealKeys(api);
		
		jQuery("input[type=text], input[type=password]").keyup(function(e) {
			if (e.keyCode != 13) {
				if (jQuery(this).validate(api)) {
					jQuery(this).parents(".step").find(".next span").stop(true, false).animate({"marginRight": 0}, 500);
				} else {
					jQuery(this).parents(".step").find(".next span").stop(true, false).animate({"marginRight": -85}, 500);
				}
			}
		});
		
		jQuery(".step.three input[type=checkbox]").change(function() {
			if ( jQuery(this).attr("id") == "all" ) {
				if ( jQuery(this).attr("checked") ) {
					jQuery(this).parents(".step").find("input[type=checkbox]").not("#agree").attr("checked", true);
				} else {
					jQuery(this).parents(".step").find("input[type=checkbox]").not("#agree").attr("checked", false);
				}
			} else if ( jQuery(this).attr("id") == "agree" ) {
				if (jQuery(this).validate(api)) {
					jQuery(this).parents(".step").find(".next span").removeClass("disabled").stop(true, false).animate({"marginRight": 0}, 500);
				} else {
					jQuery(this).parents(".step").find(".next span").stop(true, false).animate({"marginRight": -85}, 500);
				}
				/*
				if ( jQuery(this).attr("checked") ) {
					jQuery(this).parents(".step.three").find("input[type=submit]").removeClass("disabled");
				} else {
					jQuery(this).parents(".step.three").find("input[type=submit]").addClass("disabled");
				}
				*/
			} else {
				jQuery(".step.three #all").attr("checked", false);
			}
		});
		
		jQuery(".step.three input[type=checkbox]:not('#agree')").attr("checked", true);
		
	});
	
</script>